version: '3.2'
services:
    datascience-notebook:
        image: jupyter:0.0.3
        volumes:
            - /Users/path:/app/
        ports:
            - "8888:8888"
        command: "jupyter notebook --port=8888 --ip=0.0.0.0 --NotebookApp.allow_remote_access=True --allow-root --NotebookApp.token='' --NotebookApp.password=''"
        user: root
        environment:
          NB_USER: docker_worker
          NB_UID: 1008
          NB_GID: 1011
          CHOWN_HOME: 'yes'
          CHOWN_HOME_OPTS: -R
